#!/usr/bin/env python3
"""
Executable full-round restricted-key Grover validation for Kalyna.

The marked set is generated by the official Kalyna reference implementation
compiled by the CI workflow.  The full 10-round Kalyna-128/128 or 14-round
Kalyna-128/256 encryption is therefore retained exactly; only the number u of
unknown master-key bits is restricted.

After the marked set is obtained, Grover amplitudes are simulated explicitly
on the 2^u candidate-key register and compared with the closed-form success
probability.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
from pathlib import Path


def run_scan(scanner: Path, key_bits: int, u: int, pairs: int) -> dict:
    cp = subprocess.run(
        [str(scanner), str(key_bits), str(u), str(pairs)],
        check=True,
        text=True,
        capture_output=True,
    )
    lines = [x.strip() for x in cp.stdout.splitlines() if x.strip()]
    if not lines:
        raise RuntimeError("scanner produced no JSON output")
    return json.loads(lines[-1])


def optimal_integer_iterations(N: int, M: int) -> tuple[int, float]:
    theta = math.asin(math.sqrt(M / N))
    center = math.pi / (4.0 * theta) - 0.5
    lo = max(0, int(math.floor(center)) - 5)
    hi = int(math.ceil(center)) + 5
    best_j = 0
    best_p = -1.0
    for j in range(lo, hi + 1):
        p = math.sin((2 * j + 1) * theta) ** 2
        if p > best_p:
            best_j, best_p = j, p
    return best_j, best_p


def explicit_grover_one_marked(N: int, marked: int, iterations: int) -> float:
    amp = 1.0 / math.sqrt(N)
    state = [amp] * N
    for _ in range(iterations):
        state[marked] = -state[marked]
        mean = sum(state) / N
        twice = 2.0 * mean
        for i, a in enumerate(state):
            state[i] = twice - a
    return state[marked] * state[marked]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--scanner", type=Path, required=True)
    ap.add_argument("--outdir", type=Path, default=Path("outputs/fullround_validation"))
    ap.add_argument("--unknown-bits", default="8,10,12,14")
    ap.add_argument(
        "--include-minimal",
        action="store_true",
        help="also scan the constant-multiplicity minimal-pair predicates",
    )
    args = ap.parse_args()

    us = [int(x) for x in args.unknown_bits.split(",") if x.strip()]
    args.outdir.mkdir(parents=True, exist_ok=True)

    # unique-key/historical-key baselines under the ideal-cipher analysis
    jobs = [(128, 2, "historical-key"), (256, 3, "historical-key")]
    if args.include_minimal:
        jobs += [(128, 1, "minimal-pair"), (256, 2, "minimal-pair")]

    rows: list[dict] = []
    for key_bits, pairs, model in jobs:
        for u in us:
            scan = run_scan(args.scanner, key_bits, u, pairs)
            if not scan.get("official_kat_pass"):
                raise AssertionError(f"official KAT failed: {scan}")
            N = int(scan["candidates"])
            M = int(scan["marked_count"])

            row = dict(scan)
            row["model"] = model

            if model == "historical-key":
                if M != 1 or scan["first_marked"] != 0 or scan["last_marked"] != 0:
                    raise AssertionError(
                        "historical-key restricted subspace is not uniquely marked: "
                        + json.dumps(scan, sort_keys=True)
                    )
                j, p_formula = optimal_integer_iterations(N, M)
                p_num = explicit_grover_one_marked(N, 0, j)
                err = abs(p_num - p_formula)
                if err > 2e-12:
                    raise AssertionError(
                        f"Grover formula/state mismatch for 128/{key_bits}, u={u}: {err}"
                    )
                row.update(
                    optimal_iterations=j,
                    closed_form_success=p_formula,
                    explicit_sparse_success=p_num,
                    absolute_error=err,
                )
            else:
                # The restricted subspace can be unique even when the full key
                # space has constant expected multiplicity.  We therefore only
                # report its observed marked count and do not use it to infer
                # full-space identifiability.
                row.update(
                    optimal_iterations=None,
                    closed_form_success=None,
                    explicit_sparse_success=None,
                    absolute_error=None,
                )
            rows.append(row)
            print(json.dumps(row, sort_keys=True))

    out_json = args.outdir / "fullround_sparse_results.json"
    out_json.write_text(json.dumps(rows, indent=2, sort_keys=True) + "\n")

    out_csv = args.outdir / "fullround_sparse_results.csv"
    fields = [
        "variant", "model", "key_bits", "unknown_bits", "pairs", "candidates",
        "marked_count", "first_marked", "optimal_iterations",
        "closed_form_success", "explicit_sparse_success", "absolute_error",
        "official_kat_pass",
    ]
    with out_csv.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)

    hist = [r for r in rows if r["model"] == "historical-key"]
    report = [
        "# Full-round restricted-key Kalyna validation",
        "",
        "The candidate predicate is evaluated by the pinned official Kalyna reference",
        "implementation.  All cipher rounds and the full key schedule are retained;",
        "only an affine subspace of the master-key bits is searched.",
        "",
        "| Variant | u | Candidates | Pairs | Marked | j* | Closed form | Explicit sparse | Error |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for r in hist:
        report.append(
            f"| {r['variant']} | {r['unknown_bits']} | {r['candidates']} | "
            f"{r['pairs']} | {r['marked_count']} | {r['optimal_iterations']} | "
            f"{r['closed_form_success']:.15f} | "
            f"{r['explicit_sparse_success']:.15f} | {r['absolute_error']:.3e} |"
        )
    report += [
        "",
        "Scope: this experiment validates the full-round known-plaintext predicate",
        "and Grover amplitude dynamics in restricted master-key subspaces. It does",
        "not by itself certify the internal ancilla cleanup or the resource count of",
        "the ProjectQ reversible implementation.",
    ]
    (args.outdir / "fullround_sparse_report.md").write_text("\n".join(report) + "\n")


if __name__ == "__main__":
    main()
